from __future__ import annotations

import copy
import re


def generated_source_counterpart(path, files):
    """Recognize top-level library outputs by build headers, not lib alone."""
    if (not path.startswith("lib/") or path.count("/") != 1
            or not path.endswith((".js", ".cjs", ".mjs"))):
        return None
    header = files.get(path, "")[:3000].lower()
    if not any(marker in header for marker in (
        "do not edit", "automatically generated", "generated by", "generated file",
    )):
        return None
    name = path.rsplit("/", 1)[-1]
    stem = re.sub(r"(?:\.(?:esm|umd|min|bundle))?\.(?:cjs|mjs|js)$", "", name)
    target = "src/" + stem + ".js"
    return target if target in files else None


def demote_generated_outputs(ranked, *, files, issue_text):
    # An explicit request to change a build output takes precedence.
    if re.search(r"\b(?:update|modify|edit|regenerate|rebuild)\b.{0,60}\b(?:bundle|generated|dist|build output)\b",
                 issue_text, re.IGNORECASE):
        return ranked, []
    mappings = []
    outputs = set()
    for item in ranked:
        target = generated_source_counterpart(item.path, files)
        if target:
            outputs.add(item.path)
            mappings.append({"artifact": item.path, "source": target,
                             "reason": "generated_header_with_source_counterpart"})
    return ([item for item in ranked if item.path not in outputs]
            + [item for item in ranked if item.path in outputs]), mappings


def restore_seed_frontier(ranked, seeds, *, index, review, top_k, limit=2):
    """Preserve entry-point priors without duplicating or inventing paths.

    Downstream responsibility verification may still promote a challenger.
    Missing evidence is not counterevidence against an otherwise valid seed.
    """
    from mycode.dynamic_retrieval.search_agent import _CLOSURE_BLOCKED_ROLES, _path_role

    decisions = {row.get("path"): row for row in review.get("candidates", [])}
    recalled = {row.path: row for row in ranked}
    chosen = []
    rejected = []
    for seed in seeds:
        if len(chosen) >= limit:
            break
        path = seed.path
        decision = decisions.get(path, {})
        reason = None
        if path not in index.files or not index.files[path].strip():
            reason = "source_unavailable"
        elif (_path_role(path) in _CLOSURE_BLOCKED_ROLES
              or generated_source_counterpart(path, index.files)):
            reason = "non_implementation_role"
        elif decision.get("grounded") and any(
            code not in {"no_source", "no_entity", "no_flow", "none"}
            for code in decision.get("counterevidence", [])
        ):
            reason = "grounded_counterevidence"
        if reason:
            rejected.append({"path": path, "reason": reason})
            continue
        if path not in {item.path for item in chosen}:
            item = copy.deepcopy(recalled.get(path, seed))
            item.reasons.append("retained_fast_seed_prior")
            chosen.append(item)
    retained = {item.path for item in chosen}
    ordered = chosen + [item for item in ranked if item.path not in retained]
    return ordered[:top_k], {
        "strategy": "bounded_seed_prior_then_dynamic_recall",
        "retained": [item.path for item in chosen],
        "rejected": rejected,
        "limit": limit,
    }
