#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Load reproducible runtime defaults without overriding explicit shell values.
# shellcheck disable=SC1091
source "$ROOT/newtest/model_config.sh"
load_env_defaults "$ROOT/configs/runtime/full_mm.env"

resolve_samples() {
  local filename="$1"
  local candidate
  for candidate in \
    "$ROOT/data/$filename" \
    "$ROOT/../clean_subsets_new/$filename" \
    "$ROOT/../../clean_subsets_new/$filename"
  do
    if [[ -f "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  # Preserve a useful error path when the caller has not copied the dataset yet.
  printf '%s\n' "$ROOT/../clean_subsets_new/$filename"
}

case "${MAGNET_DATASET_KIND:-swe}" in
  swe)
    SAMPLE_FILENAME="swebench_multimodal-full-dev.clean15.samples.jsonl"
    DEFAULT_DATASET="swebench_multimodal-full-dev-clean15"
    DEFAULT_RUN_PREFIX="swe_clean15_addtest"
    AGENT_LAUNCHER="$ROOT/newtest/run_swe_clean15_agent_full.sh"
    ;;
  omni)
    SAMPLE_FILENAME="omnigirl-full-candidates.clean15.v458.samples.jsonl"
    DEFAULT_DATASET="omnigirl-full-candidates-clean15"
    DEFAULT_RUN_PREFIX="omni_clean15_addtest"
    AGENT_LAUNCHER="$ROOT/newtest/run_omni_clean15_agent_full.sh"
    ;;
  *)
    echo "Unsupported MAGNET_DATASET_KIND: ${MAGNET_DATASET_KIND}" >&2
    exit 2
    ;;
esac

export DEEP_AGENT="${DEEP_AGENT:-1}"
export LIGHTWEIGHT="${LIGHTWEIGHT:-0}"
export STRUCTURE_ONLY="${STRUCTURE_ONLY:-1}"
export FULL_MM="${FULL_MM:-1}"
export MYCODE_BROWSER_REQUIRED="${MYCODE_BROWSER_REQUIRED:-1}"
export MYCODE_REQUIRE_SOURCE_CHECKOUT="${MYCODE_REQUIRE_SOURCE_CHECKOUT:-1}"
export SAMPLES="${SAMPLES:-$(resolve_samples "$SAMPLE_FILENAME")}"
export DATASET="${DATASET:-$DEFAULT_DATASET}"
export RUN_ID="${RUN_ID:-${DEFAULT_RUN_PREFIX}_$(date +%Y%m%d_%H%M%S)}"
export RESUME="${RESUME:-0}"

export VERBOSE_AGENT_LOG="${VERBOSE_AGENT_LOG:-1}"
export VERBOSE_AGENT_LIMIT="${VERBOSE_AGENT_LIMIT:-6}"
export VERBOSE_LLM_TEXT_LIMIT="${VERBOSE_LLM_TEXT_LIMIT:-500}"
export MYCODE_PHASE_LOG="${MYCODE_PHASE_LOG:-1}"
export DYNAMIC_ROUNDS="${DYNAMIC_ROUNDS:-14}"
export MAX_TOOL_ROUNDS="${MAX_TOOL_ROUNDS:-6}"
export MAX_REACT_STEPS="${MAX_REACT_STEPS:-10}"
export TOP_K="${TOP_K:-15}"
export SAMPLE_TIMEOUT_SECONDS="${SAMPLE_TIMEOUT_SECONDS:-3000}"

export MYCODE_DEEP_GRAPH_SCOPE="${MYCODE_DEEP_GRAPH_SCOPE:-160}"
export MYCODE_DEEP_PREFILTER_QUERY_BUDGET="${MYCODE_DEEP_PREFILTER_QUERY_BUDGET:-64}"
export MYCODE_DEEP_PREFILTER_MULTIPLIER="${MYCODE_DEEP_PREFILTER_MULTIPLIER:-8}"
export MYCODE_ROUND_POOL_LIMIT="${MYCODE_ROUND_POOL_LIMIT:-128}"
export MYCODE_ROUND_GLOBAL_FILE_HITS="${MYCODE_ROUND_GLOBAL_FILE_HITS:-36}"
export MYCODE_ROUND_GLOBAL_ENTITY_HITS="${MYCODE_ROUND_GLOBAL_ENTITY_HITS:-48}"
export MYCODE_GLOBAL_CHANNEL_FILE_HITS="${MYCODE_GLOBAL_CHANNEL_FILE_HITS:-12}"
export MYCODE_GLOBAL_CHANNEL_ENTITY_HITS="${MYCODE_GLOBAL_CHANNEL_ENTITY_HITS:-14}"
export MYCODE_ROUND_READ_BUDGET="${MYCODE_ROUND_READ_BUDGET:-32}"
export MYCODE_CODE_CONTEXT_LIMIT="${MYCODE_CODE_CONTEXT_LIMIT:-16}"
export MYCODE_ENTITY_RERANK_POOL="${MYCODE_ENTITY_RERANK_POOL:-80}"
export MYCODE_LLM_CANDIDATE_REVIEW="${MYCODE_LLM_CANDIDATE_REVIEW:-1}"
export MYCODE_LLM_REVIEW_CANDIDATES="${MYCODE_LLM_REVIEW_CANDIDATES:-6}"
export MYCODE_LLM_REVIEW_REPAIR_ATTEMPTS="${MYCODE_LLM_REVIEW_REPAIR_ATTEMPTS:-2}"
export MYCODE_CANDIDATE_REVIEW_MAX_TOKENS="${MYCODE_CANDIDATE_REVIEW_MAX_TOKENS:-1200}"
export MYCODE_REACT_ENFORCE_TOOL_COVERAGE="${MYCODE_REACT_ENFORCE_TOOL_COVERAGE:-0}"

export MYCODE_FLOW_POOL_LIMIT="${MYCODE_FLOW_POOL_LIMIT:-64}"
export MYCODE_FLOW_TRACE_LIMIT="${MYCODE_FLOW_TRACE_LIMIT:-6}"
export MYCODE_FLOW_MODE="${MYCODE_FLOW_MODE:-auto}"
export MYCODE_DEEP_FLOW_AUTO="${MYCODE_DEEP_FLOW_AUTO:-1}"
export MYCODE_DEEP_FLOW_CANDIDATE_LIMIT="${MYCODE_DEEP_FLOW_CANDIDATE_LIMIT:-32}"
export MYCODE_INTERPROCEDURAL_MAX_HOPS="${MYCODE_INTERPROCEDURAL_MAX_HOPS:-2}"

export MYCODE_ARCHITECTURE_PATH_WEIGHT="${MYCODE_ARCHITECTURE_PATH_WEIGHT:-0.8}"
export MYCODE_ROUND_ARCHITECTURE_PATH_LIMIT="${MYCODE_ROUND_ARCHITECTURE_PATH_LIMIT:-16}"
export MYCODE_ARCHITECTURE_CORROBORATION="${MYCODE_ARCHITECTURE_CORROBORATION:-1}"
export MYCODE_FAST_SEED_PLANNER="${MYCODE_FAST_SEED_PLANNER:-1}"
export MYCODE_FAST_SEED_LLM="${MYCODE_FAST_SEED_LLM:-1}"
export MYCODE_FAST_SEED_CANDIDATES="${MYCODE_FAST_SEED_CANDIDATES:-10}"
export MYCODE_FAST_SEED_SHORTLIST="${MYCODE_FAST_SEED_SHORTLIST:-6}"
export MYCODE_FAST_SEED_LIMIT="${MYCODE_FAST_SEED_LIMIT:-3}"
export MYCODE_MEMORY_ROUND_DECAY="${MYCODE_MEMORY_ROUND_DECAY:-0.90}"
export MYCODE_MEMORY_NO_GAIN_DECAY="${MYCODE_MEMORY_NO_GAIN_DECAY:-0.75}"

export MYCODE_BEST_ROUND_CHECKPOINT="${MYCODE_BEST_ROUND_CHECKPOINT:-1}"
export MYCODE_BEST_ROUND_MIN_GAIN="${MYCODE_BEST_ROUND_MIN_GAIN:-0.10}"
export MYCODE_CROSS_ROUND_FRONTIER="${MYCODE_CROSS_ROUND_FRONTIER:-1}"
export MYCODE_CROSS_ROUND_LOCKED_HEAD="${MYCODE_CROSS_ROUND_LOCKED_HEAD:-2}"
export MYCODE_CROSS_ROUND_MAX_REPLACEMENTS="${MYCODE_CROSS_ROUND_MAX_REPLACEMENTS:-4}"
export MYCODE_CROSS_ROUND_PROTECTED_PREFIX="${MYCODE_CROSS_ROUND_PROTECTED_PREFIX:-6}"
export MYCODE_CROSS_ROUND_PER_ROUND_LIMIT="${MYCODE_CROSS_ROUND_PER_ROUND_LIMIT:-15}"
export MYCODE_CROSS_ROUND_REPLACEMENT_MARGIN="${MYCODE_CROSS_ROUND_REPLACEMENT_MARGIN:-0.75}"
export MYCODE_PRECISION_RERANK="${MYCODE_PRECISION_RERANK:-1}"
export MYCODE_HEAD_REPLACEMENT_MARGIN="${MYCODE_HEAD_REPLACEMENT_MARGIN:-3.0}"

export MYCODE_EARLY_STOP_HIGH_CONFIDENCE="${MYCODE_EARLY_STOP_HIGH_CONFIDENCE:-1}"
export MYCODE_HIGH_CONFIDENCE_THRESHOLD="${MYCODE_HIGH_CONFIDENCE_THRESHOLD:-0.84}"
export MYCODE_EARLY_STOP_EVIDENCE_PLATEAU="${MYCODE_EARLY_STOP_EVIDENCE_PLATEAU:-1}"
export MYCODE_EVIDENCE_PLATEAU_ROUNDS="${MYCODE_EVIDENCE_PLATEAU_ROUNDS:-2}"
export MYCODE_PLATEAU_REVIEW_OVERRIDE_ROUND="${MYCODE_PLATEAU_REVIEW_OVERRIDE_ROUND:-12}"
export MYCODE_PLATEAU_TOP5_OVERLAP="${MYCODE_PLATEAU_TOP5_OVERLAP:-0.75}"
export MYCODE_REACT_NO_GAIN_STEPS="${MYCODE_REACT_NO_GAIN_STEPS:-2}"
export MYCODE_AGENT_FOLLOWUP_MODE="${MYCODE_AGENT_FOLLOWUP_MODE:-on_demand}"
export MYCODE_AGENT_FOLLOWUP_CONFIDENCE="${MYCODE_AGENT_FOLLOWUP_CONFIDENCE:-0.68}"

export MYCODE_FINAL_PATCH_SET_LIMIT="${MYCODE_FINAL_PATCH_SET_LIMIT:-5}"
export MYCODE_CLOSURE_MAX_ROUNDS="${MYCODE_CLOSURE_MAX_ROUNDS:-4}"
export MYCODE_CLOSURE_EXPAND_PER_ROUND="${MYCODE_CLOSURE_EXPAND_PER_ROUND:-2}"
export MYCODE_PARTIAL_SET_FALLBACK="${MYCODE_PARTIAL_SET_FALLBACK:-1}"

cd "$ROOT"
exec bash "$AGENT_LAUNCHER" "$@"
